### PR TITLE
Add "Log This" achievement

### PR DESCRIPTION
**Pull request by lucaspotter**
Log4Shell was quite the vulnerability.

### CODE REVIEW

**Review by seanpm2001 — APPROVED** [review]
Nice

**Review by dlbone — APPROVED** [review]

**Review by Schweinepriester — APPROVED** [review]
@Flet I think this one is good to go :)

**Comment by steadweb** [comment]
+1

**Review by Flet — APPROVED** [review]

**Comment by Flet** [comment]
Achievement Unlocked: Get a PR you forgot about merged 6 months later

Hah, seriously though thanks @lucaspotter badge looks great!

**Pull request merged**
